class PackWater:
    def __init__(self, nummol, lencube=None, density=None):
        """ Constructor for the WaterPack class.
        
        Parameters
        ----------
        nummol : int   
            number of molecules. Note: this is not necessarily
            equal to the number of particles in the MD-sim.
        lencube : float
            length of packed cube given in Å (Ångstrøm).
        """
        if lencube is None and density is None:
            raise Warning("Warning! Neither lencube nor density is given, continue with density 1 g/cm^3")
            density = 1.0
            lencube = self.den2len(density=density)
        elif lencube is not None and density is not None:
            raise Warning("Warning! Both lencube and density are given, ignoring the box length.")
            lencube = self.den2len(density=density)
        elif density is not None:
            lencube = self.den2len(density=density)
        self.nummol = nummol
        self.lencube = lencube
        
    def den2len(self, density):
        """ Returns the length of the cube given the density.
        
        Parameters
        ----------
        density : float   
            desired density of water. Unit g/cm^3
        """
        self.density = density
        self.mass_H2O = 18.0152     # Mass of H2O molecule, g/mol
        NA = 6.02214075e23          # Avogadro's number, mol^-1
        self.total_mass = self.nummol * self.mass_H2O / NA  # Total mass, g
        self.volume = self.total_mass / density             # Volume, cm^3
        length = self.volume**(1/3.)                        # Length, cm
        lencube = length * 1e8                              # Length, Å
        return lencube
        
        
    def packmol_gen(self, infile="packmol/input.in", 
                          outfile="packmol/water_packmol.data", 
                          filetype="xyz",
                          structure="water.xyz",
                          tolerance=2.0,
                          pbc=None):
        """ Generate Packmol input script. 
        
        Parameters
        ----------
        infile : str
            file that we write to.
        outfile : str
            file generated when running packmol script.
        filetype : str
            type of output file. Must match structure file.
        structure : str
            file that determines the structure of a single water molecule.
        tolerance str
            minimum distance between molecules. 2.0 default.
        pbc : float
            width of gap at boundary given in [Å].
        """
        
        import os
        try:
            # Create target Directory
            os.makedirs("packmol")
            #print("Directory ", path, " created")
        except FileExistsError:
            pass
            #print("Directory ", path, " already exists")
        
        self.infile = infile
        self.outfile = outfile
        self.lenbox = self.lencube      # lencube is length of water bulk
        if pbc is not None:
            self.lencube -= pbc
            
        
        
        f = open(infile, "w")
        f.write("tolerance {}\n".format(tolerance))
        f.write("output {}\n".format(outfile))
        f.write("filetype {}\n".format(filetype))
        f.write("structure {}\n".format(structure))
        f.write("  number {}\n".format(self.nummol))
        f.write("  inside cube 0. 0. 0. {}\n".format(self.lencube))
        f.write("end structure\n")
        f.close()
        print("Generated file " + infile)
        
    def xyz2lmp(self, out="../data/water_lmps.data"):
        """ Convert the packmol outfile (on xyz filetype) to Lammps readable
        file.
        
        Arguments:
        ----------
        out : str
            output file after converting.
        """
        with open(out, 'w') as outfile:
            # Write header
            outfile.write(out + " (Built by Packmol)\n\n")
            outfile.write("{} atoms\n".format(3*self.nummol))
            outfile.write("2 atom types\n")
            outfile.write("0.0          {} xlo xhi\n".format(self.lenbox))
            outfile.write("0.0          {} ylo yhi\n".format(self.lenbox))
            outfile.write("0.0          {} zlo zhi\n\n".format(self.lenbox))
            outfile.write("Atoms\n\n")
            # Write positions
            with open(self.outfile, 'r') as infile:
                for i, line in enumerate(infile):
                    if i > 1:
                        line = str(i-1) + line
                        line = line.replace("H", "1")
                        line = line.replace("O", "2")
                        outfile.write(line)
        print("Converted from xyz-filetype to LAMMPS-friendly filetype, {}".format(out))
        
    def __call__(self, outfile="water_config.data",
                       filetype="lammps",
                       pbc=None,
                       tolerance=2.0):
        """ Run the Packmol input script generated by self.packmol_gen.
        """
        self.packmol_gen(outfile=outfile, filetype="xyz", pbc=pbc, tolerance=tolerance)
        
        from os import system
        call_string = "packmol < {}".format(self.infile)
        system(call_string)
        print("Packmol script run and file {} generated".format(self.outfile))
                    
if __name__ == "__main__":

    ### EXAMPLE SCRIPT
    packer = PackWater(nummol=2000, density=0.998)
    packer.packmol_gen(pbc=1.0)
    packer()
    packer.xyz2lmp(out="water_lammps.data")
